config/routes.rb
Rails.application.routes.draw do

  resources :sky_reward_services
  get 'main/index'

  resources :customers
  resources :portfolios
  resources :rewards
  resources :channel_subscriptions

  root 'main#index'

  post 'main/form_input'
  get 'main/reward_service_output'

  

end

app/models/channel_subscription.rb
class ChannelSubscription < ActiveRecord::Base

  has_many :customer_subscriptions
  has_many :customers, through: :customer_subscriptions

  belongs_to :portfolio 

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  GOOD_BILLING_STATUS = "GOOD" # Either GOOD or BAD
  ACCEPTABLE_LOYALTY_RATING = 2 # 1..5

  attr_reader :loyalty_rating, :billing_status

  has_many :customer_subscriptions
  has_many :channel_subscriptions, through: :customer_subscriptions


  def self.loyal?

    loyalty_rating >= ACCEPTABLE_LOYALTY_RATING

  end

  def self.has_good_billing_status?

    billing_status == GOOD_BILLING_STATUS

  end
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base

  has_many :channel_subscriptions

end

app/models/reward.rb
=begin

  Author: Hossein Mirzapour 

  Reward class provides an Enumerable for rewards associated to subscriptions

=end

class Reward

  CHAMPIONS_LEAGUE_FINAL_TICKET = "Champions League Final Ticket"
  KARAOKE_PRO_MICROPHONE = "Karaoke Pro Microphone"
  PIRATES_OF_THE_CARIBBEAN_COLLECTION = "Pirates Of The Caribbean Collection"
  REWARD_NOT_AVAILABLE = "No Rewards"

  include Enumerable

  def each
    yield   ["SPORTS",  CHAMPIONS_LEAGUE_FINAL_TICKET]
    yield   ["KIDS",  REWARD_NOT_AVAILABLE]
    yield   ["MUSIC",  KARAOKE_PRO_MICROPHONE]
    yield   ["NEWS",  REWARD_NOT_AVAILABLE]
    yield   ["MOVIES",  PIRATES_OF_THE_CARIBBEAN_COLLECTION]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :portfolio_map


  def portfolio_map

    @portfolios = Array.new

    Portfolio.all.each do |portfolio|

      @portfolios << [ portfolio.name, portfolio.id]

    end

  end

end

app/controllers/main_controller.rb
=begin

    Author: Hossein Mirzapour
  
    Main Controller dealing with user interface parameters and obtaining results from services


=end

class MainController < ApplicationController

  # include MainUtilities
  # Parameters sent from the view

  def form_input

    account_number = params[:account_number]

    portfolio = params[:portfolio]


    customer = SkyEligibilityService.new account_number
    

    begin

        if customer.eligible?

            reward_service = SkyRewardService.new account_number, portfolio
            
            redirect_to  main_reward_service_output_path status: "success", message: "You Are Eligible!" , result: reward_service.rewards

        else

            redirect_to  main_reward_service_output_path status: "danger", message: "You Are Not Eligible!" , result: "No Reward"

        end


    rescue Exception => e
         
         redirect_to  main_reward_service_output_path status: "danger", message: "Error" , result: e

    end 


    end

    # RewardServiceInterface.new account_number, portfolio


  def reward_service_output 

    @result = params[:result]
    @status = params[:status]
    @message = params[:message]

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RewardService</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container well main" >
  <div class="row reward_image">
    <div class="col-md-6"><%= image_tag("rewards.png", alt: "Sky Rewards") %></div>
    <div class="col-md-6">
        <%= bootstrap_form_tag url: main_form_input_path, layout: :horizontal, label_col: "col-sm-3", control_col: "col-sm-7" do |f| %>

          <%= f.text_field :account_number, placeholder: '123', label: "Account", help: "Account number must 3 digits" %>

          <%= f.select :portfolio, @portfolios , { class: "selectpicker" } %>

          <%= f.form_group do %>
            <%= f.submit "Are You Eligible?" %>
          <% end %>

        <% end %>
    </div>
  </div>

  <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-4 alert alert-info alert_box">
        <div class="page-header">
          <h3>Reward Service <small>Information</small></h3>
        </div>
        The database contains 200 customers with account numbers ranging from from Sky0000 to Sky000199.
        Even number customers are eligible and odd number customers are ineligible
      </div>
      <div class="col-md-1"></div>
      
      <%= yield %>

  </div>

</div>





</body>
</html>

app/views/main/index.html.erb
<div class="col-sm-5 alert alert-warning alert_box" style="min-height:200px">

  <div class="page-header">
    <h3>Output </h3>
  </div>
  <small>Output will print here</small>
</div>